language: php
sudo: enabled
env: SYMFONY_DEPRECATIONS_HELPER=disabled
matrix:
  fast_finish: true
  include:
    - php: 7.1
services:
  - mysql
cache:
  directories:
    - $HOME/.composer/cache/files
before-install:
  - composer self-update
install:
  - composer install
  - mv .env.orig .env
  - mv phpunit.xml.orig phpunit.xml
before_script:
  - php bin/console doctrine:database:create --no-interaction
  - php bin/console doctrine:migrations:migrate --no-interaction
  - php bin/console doctrine:fixtures:load --no-interaction
  - php bin/console doctrine:database:create --env=test --no-interaction
  - php bin/console doctrine:migrations:migrate --env=test --no-interaction
  - php bin/console doctrine:fixtures:load --env=test --no-interaction
script:
  - vendor/bin/phpunit --config=phpunit.xml